---
apiVersion: v1
kind: Namespace
metadata:
  name: helmrelease-git-test
---
apiVersion: apps.open-cluster-management.io/v1
kind: HelmRelease
metadata:
  name: guestbook
  namespace: helmrelease-git-test
repo:
  chartName: nginx-chart
  source:
    github:
      branch: main
      chartPath: /test/github/nginx-chart-upgrade/nginx-chart
      urls:
        - https://github.com/stolostron/multicloud-operators-subscription-release.git
    type: git
  version: 0.2.0
