---
apiVersion: v1
kind: Namespace
metadata:
  name: helmrelease-helmrepo-test
---
apiVersion: apps.open-cluster-management.io/v1
kind: HelmRelease
metadata:
  name: guestbook
  namespace: helmrelease-helmrepo-test
repo:
  chartName: nginx-chart
  source:
    helmRepo:
      urls:
        - https://raw.githubusercontent.com/stolostron/multicloud-operators-subscription-release/main/test/helmrepo/nginx-chart-0.2.0.tgz
    type: helmrepo
  version: 0.2.0
