---
apiVersion: v1
kind: Namespace
metadata:
  name: helmrelease-spec-test
---
apiVersion: apps.open-cluster-management.io/v1
kind: HelmRelease
metadata:
  name: guestbook
  namespace: helmrelease-spec-test
repo:
  chartName: nginx-chart
  source:
    github:
      branch: gh-pages
      chartPath: nginx-chart
      urls:
        - https://github.com/pezhang/helm-release-API-test.git
    type: git
  version: 0.1.0
spec:
  replicaCount: 4
